import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] });
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> 
        <header className="site-header">
          <div className="container-center flex items-center justify-between py-4">
            <div className="flex items-center gap-4">
              <Link href="/" className="site-logo">JerseyRetroBola</Link>
              <nav className="nav hidden md:flex">
                <Link href="/" className="nav-link">Beranda</Link>
                <Link href="/products" className="nav-link">Produk</Link>
                <Link href="/info" className="nav-link">Info</Link>
              </nav>
            </div>

            <div className="flex items-center gap-3">
              <Link href="/login" className="btn-outline">Login</Link>
              <Link href="/register" className="btn-primary">Daftar</Link>
            </div>
          </div>
        </header>

        <main className="container-center py-10">{children}</main>
      </body>
    </html>
  );
}
