import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-black/95 text-white glass">
          <nav className="container-center flex items-center justify-between py-4">
            <Link href="/" className="text-lg font-semibold tracking-wide">
              JerseyRetroBola
            </Link>
            <div className="flex gap-6 items-center">
              <Link href="/" className="text-sm muted hover:text-white">
                Beranda
              </Link>
              <Link href="/products" className="text-sm muted hover:text-white">
                Produk
              </Link>
              <Link href="/info" className="text-sm muted hover:text-white">
                More Info
              </Link>
              <Link href="/login" className="text-sm btn-outline">
                Login
              </Link>
            </div>
          </nav>
        </header>

        <main className="container-center py-8">{children}</main>
      </body>
    </html>
  );
}
