import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="border-b bg-white/60 px-6 py-4 shadow-sm">
          <nav className="mx-auto flex max-w-5xl items-center justify-between">
            <Link href="/" className="text-lg font-semibold">
              JerseyRetroBola
            </Link>
            <div className="flex gap-3 items-center">
              <Link href="/" className="rounded px-3 py-1 hover:bg-gray-100">
                Beranda
              </Link>
              <Link href="/products" className="rounded px-3 py-1 hover:bg-gray-100">
                Produk
              </Link>
              <Link href="/info" className="rounded px-3 py-1 hover:bg-gray-100">
                More Info
              </Link>
              <Link href="/login" className="rounded px-3 py-1 hover:bg-gray-100">
                Login
              </Link>
              <Link href="/register" className="rounded border px-3 py-1 hover:bg-gray-50">
                Register
              </Link>
            </div>
          </nav>
        </header>
        <main className="mx-auto max-w-5xl p-6">{children}</main>
      </body>
    </html>
  );
}
